### ISSUE TITLE
Deprecate `cwltool --pack` in favor of `cwlpack` from sbpack

### ISSUE THREAD

**Issue by mr-c** [common-workflow-language/cwltool#1611]
Open `--pack` related issues to confirm that `cwlpack` fixes:
- [ ]  Inconsistent behaviour in packing #1470 
- [ ]  cwltool --pack generates IDs for enum symbols #1513 
- [ ]  Behavior of cwltool --pack is inconsistent when tool has an ID #1512 
- [ ]  'main/' added when 'id' not present in workflow outputs #1436 
- [ ]  Not possible to pack workflow A with reference to packed workflow B #1323 
- [ ]  cwltool pack creates invalid json when sub-attributes are named the same #1277 
- [ ]  Workflow fails validation after packing #1241 
- [ ]  Packing Error: relative path to tools are falsely handled as absolute #1240 
- [ ]  unpack a workflow #1211 
- [ ] '--pack' option fails when '--validate' works fine #1103 
- [ ]  regression: --pack, relative run references when loading from a URL #1077 
- [ ] cwltool --pack : field $schemas get lost #897 
- [ ]  Enhance --pack to replace default Files with File literals? #531
